// <auto-generated />
using System;
using ContactList.API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactList.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230419150134_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactBook.Model.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "Leati Joseph, Pensacola Florida",
                            DateOfBirth = new DateTime(1985, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "roman@wwecorp.com",
                            FirstName = "Roman",
                            Gender = 1,
                            LastName = "Reign",
                            Occupation = "Wrestler",
                            PhoneNumber = "08035003025",
                            PhotoPath = "images/reignwwe.jpg"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "Uyo Street, Port Harcourt",
                            DateOfBirth = new DateTime(1979, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@yahoo.com",
                            FirstName = "Sara",
                            Gender = 0,
                            LastName = "Field",
                            Occupation = "Doctor",
                            PhoneNumber = "08028961586",
                            PhotoPath = "images/sara.png"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "Asanjo, Lagos",
                            DateOfBirth = new DateTime(1995, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "victor@gmail.com",
                            FirstName = "Victor",
                            Gender = 1,
                            LastName = "Unachukwu",
                            Occupation = "Software Engineer",
                            PhoneNumber = "09025419260",
                            PhotoPath = "images/victor.jpg"
                        },
                        new
                        {
                            ContactId = 4,
                            Address = "Riverside, Califor nia",
                            DateOfBirth = new DateTime(1987, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ronda@wwecorp.com",
                            FirstName = "Ronda",
                            Gender = 0,
                            LastName = "Rousey",
                            Occupation = "Wrestler",
                            PhoneNumber = "08037530139",
                            PhotoPath = "images/rosey.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
